-- Personal input method keybindings.
-- Loaded by hypr/hyprland.lua after the repo's hypr/bindings.lua.
--
-- NOTE: The repo's hypr/bindings.lua already binds SUPER+SPACE / SUPER+SHIFT+SPACE
-- to input-method.cycle via sumika-action, AND registers a transparent
-- "superInterrupt" bind for every SUPER+key so that releasing Super after a
-- SUPER+<key> chord does NOT toggle the workspace overview.
--
-- A previous version of this file called hl.unbind("SUPER + SPACE") + rebind,
-- which wiped the interrupt bind and caused the overview to pop up every time
-- Super was released after an input-method switch. Since the defaults now
-- match exactly, this file intentionally adds nothing — keep it empty so the
-- repo defaults (with their interrupt binds) stay intact.