# Dotfiles 管理エイリアス
alias dotlink="bash ${HOME}/dotfiles/dotlink/dotlink"
alias dotsync="bash ${HOME}/dotfiles/dotlink/dotsync"
alias reload="exec zsh"
alias os:config="nvim $HOME/dotfiles/aliases/"
dotfiles() { cd "$HOME/dotfiles" && nvim "aliases/"; }
