# 工具脚本エイリアス
alias ytdl="bash ${HOME}/dotfiles/tools/ytdl.sh"
alias unzip:here="bash ${HOME}/dotfiles/tools/unzip_here.sh"
alias packtar="bash ${HOME}/dotfiles/tools/packtar.sh"
alias jp="bash ${HOME}/chezmoi/dot_config/dotfiles/tools/executable_jp_convert.sh"
alias rjz="trans ja:zh"
alias rzj="trans zh:ja"
alias sbzr="bash ${HOME}/chezmoi/dot_config/dotfiles/tools/executable_sbzr.sh"
