[bookmarks.alpine-practice]
protocol = "SFTP"
address = "localhost"
port = 2222
username = "student"

[bookmarks.lmde7]
protocol = "SFTP"
address = "192.168.3.62"
port = 22
username = "tetsuya"

[bookmarks.alpine-practice-scp]
protocol = "SCP"
address = "localhost"
port = 2222
username = "student"

[recents.ISO20260430T223932]
protocol = "SFTP"
address = "192.168.3.62"
port = 22
username = "tetsuya"
